// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ccEeFTqGM7N6MKNn3Axffo
// Component: eJH_pQ8jd3B-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NexusForm from "../../NexusForm"; // plasmic-import: CukkPgCkjNZW/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ccEeFTqGM7N6MKNn3Axffo/projectcss
import sty from "./PlasmicTestFormulaire.module.css"; // plasmic-import: eJH_pQ8jd3B-/css

createPlasmicElementProxy;

export type PlasmicTestFormulaire__VariantMembers = {};
export type PlasmicTestFormulaire__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestFormulaire__VariantsArgs;
export const PlasmicTestFormulaire__VariantProps = new Array<VariantPropType>();

export type PlasmicTestFormulaire__ArgsType = {};
type ArgPropType = keyof PlasmicTestFormulaire__ArgsType;
export const PlasmicTestFormulaire__ArgProps = new Array<ArgPropType>();

export type PlasmicTestFormulaire__OverridesType = {
  root?: Flex__<"div">;
  nexusForm?: Flex__<typeof NexusForm>;
};

export interface DefaultTestFormulaireProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTestFormulaire__RenderFunc(props: {
  variants: PlasmicTestFormulaire__VariantsArgs;
  args: PlasmicTestFormulaire__ArgsType;
  overrides: PlasmicTestFormulaire__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <NexusForm
            data-plasmic-name={"nexusForm"}
            data-plasmic-override={overrides.nexusForm}
            className={classNames("__wab_instance", sty.nexusForm)}
            formSlug={(() => {
              try {
                return $ctx.params.form_slug;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "nexusForm"],
  nexusForm: ["nexusForm"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  nexusForm: typeof NexusForm;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestFormulaire__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestFormulaire__VariantsArgs;
    args?: PlasmicTestFormulaire__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestFormulaire__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTestFormulaire__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestFormulaire__ArgProps,
          internalVariantPropNames: PlasmicTestFormulaire__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestFormulaire__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestFormulaire";
  } else {
    func.displayName = `PlasmicTestFormulaire.${nodeName}`;
  }
  return func;
}

export const PlasmicTestFormulaire = Object.assign(
  // Top-level PlasmicTestFormulaire renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nexusForm: makeNodeComponent("nexusForm"),

    // Metadata about props expected for PlasmicTestFormulaire
    internalVariantProps: PlasmicTestFormulaire__VariantProps,
    internalArgProps: PlasmicTestFormulaire__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTestFormulaire;
/* prettier-ignore-end */
